# Generated by Django 2.0.3 on 2018-03-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synchroalg',
            name='demourl',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
